if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi
if [ -f ~/.aliases ]; then
  source ~/.aliases
fi

export NODE_ENV=development
export LT3_ENV=dev
export LT3_PLATFORM=web

export PATH=/opt/local/bin:/opt/local/sbin:$PATH
