#!/usr/bin/bash

# Git - Filter a Directory to its own repository

git clone current new
cd new
git remote rm origin
git filter-branch --tag-name-filter cat --prune-empty --subdirectory-filter ABC -- --all
git reset --hard
git for-each-ref --format="%(refname)" refs/original/ | xargs -n 1 git update-ref -d
git reflog expire --expire=now --all
git gc --aggressive --prune=now
git remote add origin ssh://git@github.com/org/repo.git
git push -u origin master
